pokemon_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: airflow_postgres  
      user: airflow
      password: airflow
      port: 5432
      dbname: airflow
      schema: public
      threads: 1